<?php

namespace app\modules\ecitizen\services;

use app\modules\ecitizen\models\smis\SmisBankingSlip;
use app\modules\ecitizen\models\smis\SmisFeePayment;
use app\modules\ecitizen\models\smis\SmisFeeTransaction;
use Yii;
use yii\db\Connection;

/**
 * Posts a smisportal-credited eCitizen payment into the standalone `smis`
 * database, adapted from BankingSlips::postFeePayments()/postFeeTransactions()
 * in the SMIS admin app: a POSTED banking slip, a fee-transaction credit and
 * a fee payment.
 *
 * The fee-transaction/fee-payment `trans_id` is the id already generated by
 * smisportal's own fee transaction (passed in explicitly), so the two
 * databases stay joinable on trans_id for the same payment. The banking
 * slip's own `trans_id` primary key is left to smis's own auto-increment.
 * `receipt_no` is generated the same way SMIS's own BankingSlips::
 * generateReceiptNo() does it: the next value after the highest numeric
 * receipt_no already recorded on smis.fss_banking_slips/fss_fee_payments,
 * a value shared across every collection channel, not just eCitizen.
 * postCreditedPayment() returns that receipt number so the caller can
 * backfill it into the smisportal fee statement (see
 * PaymentService::attemptSmisPosting()) — matching how SMIS's own fee
 * statement report falls back to fss_fee_payments.receipt_no for the
 * "Trans ID" column when a transaction has no matching invoice.
 *
 * Callers are responsible for locking (see PaymentService::lockPosting())
 * and for never letting a failure here affect the smisportal transaction,
 * which has already committed by the time this runs.
 */
final class SmisPostingService
{
    private const LOG_CATEGORY = 'ecitizen.smis_posting';
    private const REQUIRED_TABLES = [
        'smis.fss_banking_slips',
        'smis.fss_fee_transactions',
        'smis.fss_fee_payments',
    ];

    private ?Connection $db = null;

    private function connection(): Connection
    {
        if ($this->db === null) {
            $this->db = Yii::$app->get('smisDb');
        }

        return $this->db;
    }

    public function isAlreadyPosted(string $billRefNumber): bool
    {
        if ($billRefNumber === '') {
            return false;
        }

        try {
            return SmisBankingSlip::find()->where(['source_reference' => $billRefNumber])->exists();
        } catch (\Throwable $exception) {
            Yii::error(
                'Unable to check smis posting status for ' . $billRefNumber . ': ' . $exception->getMessage(),
                self::LOG_CATEGORY
            );
            return false;
        }
    }

    /**
     * The smis.fss_banking_slips row already posted for this reference, if
     * any. Used both to short-circuit re-posting and to let callers backfill
     * its receipt_no back into the smisportal fee statement.
     */
    private function findPostedSlip(string $billRefNumber): ?SmisBankingSlip
    {
        if ($billRefNumber === '') {
            return null;
        }

        try {
            return SmisBankingSlip::find()->where(['source_reference' => $billRefNumber])->one();
        } catch (\Throwable $exception) {
            Yii::error(
                'Unable to look up smis posting for ' . $billRefNumber . ': ' . $exception->getMessage(),
                self::LOG_CATEGORY
            );
            return null;
        }
    }

    /**
     * @param array<int, string> $billRefNumbers
     * @return array<int, string> the subset already posted to smis
     */
    public function postedReferences(array $billRefNumbers): array
    {
        $billRefNumbers = array_values(array_unique(array_filter(
            $billRefNumbers,
            static fn ($value): bool => $value !== null && $value !== ''
        )));
        if ($billRefNumbers === []) {
            return [];
        }

        try {
            return SmisBankingSlip::find()
                ->select('source_reference')
                ->where(['source_reference' => $billRefNumbers])
                ->column();
        } catch (\Throwable $exception) {
            Yii::error('Unable to bulk-check smis posting status: ' . $exception->getMessage(), self::LOG_CATEGORY);
            return [];
        }
    }

    /**
     * @param array{
     *   billRefNumber: string, gatewayReference: string, registrationNumber: string,
     *   transId: int, amount: float, paymentDate: string, description: string,
     *   userId: string, academicProgressId: int, studentProgCurriculumId: int,
     *   studentSemesterSessionId: ?int, progressCode: string, payMode: int,
     *   bankId: mixed, bankNumber: mixed, branchCode: mixed, accountNo: mixed,
     *   otherNames: ?string, clientName: ?string, paymentTypeId: mixed
     * } $payment
     * @return int|null the smis receipt_no generated (or found) for this payment, or null
     *   if posting failed. Callers use this to backfill the real smis receipt number into
     *   the smisportal fee statement (see PaymentService::attemptSmisPosting()).
     */
    public function postCreditedPayment(array $payment): ?int
    {
        $billRefNumber = (string) ($payment['billRefNumber'] ?? '');
        $transId = (int) ($payment['transId'] ?? 0);
        if ($billRefNumber === '' || $transId <= 0) {
            return null;
        }

        $existingSlip = $this->findPostedSlip($billRefNumber);
        if ($existingSlip !== null) {
            $existingReceiptNo = trim((string) ($existingSlip->receipt_no ?? ''));
            return $existingReceiptNo !== '' && ctype_digit($existingReceiptNo) ? (int) $existingReceiptNo : null;
        }

        $db = $this->connection();
        if (!$this->schemaReady($db)) {
            Yii::error(
                'SMIS posting skipped for ' . $billRefNumber . ': required smis tables are not reachable.',
                self::LOG_CATEGORY
            );
            return null;
        }

        $transaction = $db->beginTransaction();
        try {
            if (!SmisFeeTransaction::find()->where(['trans_id' => $transId, 'trans_type' => 'CR'])->exists()) {
                $feeTransaction = new SmisFeeTransaction();
                $feeTransaction->setAttributes([
                    'trans_id' => $transId,
                    'academic_progress_id' => $payment['academicProgressId'],
                    'trans_date' => $payment['paymentDate'],
                    'trans_type' => 'CR',
                    'trans_amount' => $payment['amount'],
                    'trans_desc' => substr((string) $payment['description'], 0, 150),
                    'user_id' => (string) $payment['userId'],
                    'receipt_status' => '',
                    'exchange_rate' => 1,
                    'progress_code' => $payment['progressCode'],
                    'student_semester_session_id' => $payment['studentSemesterSessionId'],
                ], false);
                if (!$feeTransaction->save(false)) {
                    throw new \RuntimeException('Unable to create smis fee transaction: ' . json_encode($feeTransaction->getErrors()));
                }
            }

            $slip = new SmisBankingSlip();
            $slip->setAttributes([
                'deposit_date' => $payment['paymentDate'],
                'deposit_type' => $payment['paymentTypeId'] ?? null,
                'payment_type_id' => $payment['paymentTypeId'] ?? null,
                'deposit_amount' => $payment['amount'],
                'reg_number' => $payment['registrationNumber'],
                'registration_number' => $payment['registrationNumber'],
                'other_names' => $payment['otherNames'] ?: ($payment['clientName'] ?? ''),
                'post_status' => 'POSTED',
                'post_comment' => substr((string) $payment['description'], 0, 20),
                'account_no' => $payment['accountNo'] ?? null,
                'process_date' => date('Y-m-d'),
                'pay_mode' => $payment['payMode'],
                'trans_reference' => substr((string) ($payment['gatewayReference'] ?: $billRefNumber), 0, 50),
                'branch_code' => $payment['branchCode'] ?? null,
                'last_update' => date('Y-m-d H:i:s'),
                'user_id' => $payment['userId'] ?? null,
                'drawer_name' => 'eCitizen',
                'source_reference' => $billRefNumber,
                'value_date' => date('Y-m-d H:i:s'),
                'bank_id' => $payment['bankId'] ?? null,
                'bank_number' => $payment['bankNumber'] ?? null,
            ], false);
            if (!$slip->save(false)) {
                throw new \RuntimeException('Unable to create smis banking slip: ' . json_encode($slip->getErrors()));
            }

            $receiptNo = $this->nextReceiptNumber();
            $slip->receipt_no = $receiptNo;
            if (!$slip->save(false)) {
                throw new \RuntimeException('Unable to set smis banking slip receipt number: ' . json_encode($slip->getErrors()));
            }

            if (!SmisFeePayment::find()->where(['trans_id' => $transId])->exists()) {
                $feePaymentAttributes = [
                    'receipt_no' => (string) $receiptNo,
                    'trans_date' => $payment['paymentDate'],
                    'trans_amount' => $payment['amount'],
                    'pay_mode' => $payment['payMode'],
                    'collection_point_id' => $payment['bankId'] ?? null,
                    'user_id' => (string) $payment['userId'],
                    'entry_date' => date('Y-m-d'),
                    'trans_id' => $transId,
                    'academic_session' => '',
                    'authorized_by' => (string) $payment['userId'],
                    'authorized_date' => date('Y-m-d'),
                    'receipt_status' => '',
                    'exchange_rate' => 1,
                    'student_prog_curriculum_id' => $payment['studentProgCurriculumId'],
                ];
                if (!$this->columnHasDatabaseGeneratedValue($db, 'smis.fss_fee_payments', 'fee_paymt_id')) {
                    $feePaymentAttributes['fee_paymt_id'] = $transId;
                }

                $feePayment = new SmisFeePayment();
                $feePayment->setAttributes($feePaymentAttributes, false);
                if (!$feePayment->save(false)) {
                    throw new \RuntimeException('Unable to create smis fee payment: ' . json_encode($feePayment->getErrors()));
                }
            }

            $transaction->commit();
            return $receiptNo;
        } catch (\Throwable $exception) {
            $transaction->rollBack();
            Yii::error('SMIS posting failed for ' . $billRefNumber . ': ' . $exception->getMessage(), self::LOG_CATEGORY);
            return null;
        }
    }

    private function schemaReady(Connection $db): bool
    {
        foreach (self::REQUIRED_TABLES as $table) {
            if ($db->schema->getTableSchema($table, true) === null) {
                return false;
            }
        }

        return true;
    }

    private function columnHasDatabaseGeneratedValue(Connection $db, string $table, string $column): bool
    {
        $schema = $db->schema->getTableSchema($table, true);
        $tableColumn = $schema?->columns[$column] ?? null;

        return $tableColumn !== null && ($tableColumn->autoIncrement || $tableColumn->defaultValue !== null);
    }

    private function nextReceiptNumber(): int
    {
        $lastValue = 0;
        $receiptNumbers = array_merge(
            SmisFeePayment::find()
                ->select('receipt_no')
                ->where(['not', ['receipt_no' => null]])
                ->column(),
            SmisBankingSlip::find()
                ->select('receipt_no')
                ->where(['not', ['receipt_no' => null]])
                ->column()
        );

        foreach ($receiptNumbers as $receiptNumber) {
            $receiptNumber = trim((string) $receiptNumber);
            if ($receiptNumber !== '' && ctype_digit($receiptNumber)) {
                $lastValue = max($lastValue, (int) $receiptNumber);
            }
        }

        return $lastValue + 1;
    }
}
