<?php

namespace app\modules\ecitizen\services;

use app\modules\ecitizen\models\smis\SmisBankingSlip;
use app\modules\ecitizen\models\smis\SmisFeePayment;
use app\modules\ecitizen\models\smis\SmisFeeTransaction;
use app\modules\ecitizen\models\smis\SmisReceiptCounter;
use Yii;
use yii\db\Connection;
use yii\db\IntegrityException;

/**
 * Posts a smisportal-credited eCitizen payment into the standalone `smis`
 * database, adapted from BankingSlips::postFeePayments()/postFeeTransactions()
 * in the SMIS admin app: a POSTED banking slip, a fee-transaction credit and
 * a fee payment.
 *
 * The fee-transaction/fee-payment `trans_id` is the id already generated by
 * smisportal's own fee transaction (passed in explicitly), so the two
 * databases stay joinable on trans_id for the same payment. smis.
 * fss_fee_transactions.trans_id has no auto-increment of its own (confirmed:
 * no owned sequence, no column default) — every row there, on both this
 * integration and SMIS's own admin posting flow, always supplies trans_id
 * explicitly, sourced from smisportal. That means the explicit insert can
 * only fail if that exact id is already taken by an unrelated, pre-existing
 * smis row; see createFeeTransaction() for the fallback (find the next
 * unused trans_id on smis and use that instead) when that happens — a rare
 * case where the two databases can no longer share the same trans_id for
 * this one payment, logged clearly since it breaks the usual invariant.
 * The banking slip's own `trans_id` primary key is left to smis's own
 * auto-increment.
 * `receipt_no` is generated exactly the way SMIS's own BankingSlips::
 * generateReceiptNo() does it: the latest smis.fss_receipt_counter.last_value
 * (ordered by created_at desc) plus one, with a new counter row built but
 * only persisted once the rest of the posting succeeds — see
 * buildReceiptCounter(). This is a single counter shared across every
 * collection channel in SMIS, not just eCitizen, matching the reference
 * app precisely (it does not scan MAX(receipt_no) across other tables).
 * postCreditedPayment() returns that receipt number so the caller can
 * backfill it into the smisportal fee statement (see
 * PaymentService::attemptSmisPosting()) — matching how SMIS's own fee
 * statement report falls back to fss_fee_payments.receipt_no for the
 * "Trans ID" column when a transaction has no matching invoice.
 *
 * Callers are responsible for locking (see PaymentService::lockPosting())
 * and for never letting a failure here affect the smisportal transaction,
 * which has already committed by the time this runs.
 */
final class SmisPostingService
{
    private const LOG_CATEGORY = 'ecitizen.smis_posting';
    private const REQUIRED_TABLES = [
        'smis.fss_banking_slips',
        'smis.fss_fee_transactions',
        'smis.fss_fee_payments',
    ];

    private ?Connection $db = null;

    private function connection(): Connection
    {
        if ($this->db === null) {
            $this->db = Yii::$app->get('smisDb');
        }

        return $this->db;
    }

    public function isAlreadyPosted(string $billRefNumber): bool
    {
        if ($billRefNumber === '') {
            return false;
        }

        try {
            return SmisBankingSlip::find()->where(['source_reference' => $billRefNumber])->exists();
        } catch (\Throwable $exception) {
            Yii::error(
                'Unable to check smis posting status for ' . $billRefNumber . ': ' . $exception->getMessage(),
                self::LOG_CATEGORY
            );
            return false;
        }
    }

    /**
     * The smis.fss_banking_slips row already posted for this reference, if
     * any. Used both to short-circuit re-posting and to let callers backfill
     * its receipt_no back into the smisportal fee statement.
     */
    private function findPostedSlip(string $billRefNumber): ?SmisBankingSlip
    {
        if ($billRefNumber === '') {
            return null;
        }

        try {
            return SmisBankingSlip::find()->where(['source_reference' => $billRefNumber])->one();
        } catch (\Throwable $exception) {
            Yii::error(
                'Unable to look up smis posting for ' . $billRefNumber . ': ' . $exception->getMessage(),
                self::LOG_CATEGORY
            );
            return null;
        }
    }

    /**
     * @param array<int, string> $billRefNumbers
     * @return array<int, string> the subset already posted to smis
     */
    public function postedReferences(array $billRefNumbers): array
    {
        $billRefNumbers = array_values(array_unique(array_filter(
            $billRefNumbers,
            static fn ($value): bool => $value !== null && $value !== ''
        )));
        if ($billRefNumbers === []) {
            return [];
        }

        try {
            return SmisBankingSlip::find()
                ->select('source_reference')
                ->where(['source_reference' => $billRefNumbers])
                ->column();
        } catch (\Throwable $exception) {
            Yii::error('Unable to bulk-check smis posting status: ' . $exception->getMessage(), self::LOG_CATEGORY);
            return [];
        }
    }

    /**
     * @param array{
     *   billRefNumber: string, gatewayReference: string, registrationNumber: string,
     *   transId: int, amount: float, paymentDate: string, description: string,
     *   userId: string, academicProgressId: int, studentProgCurriculumId: int,
     *   studentSemesterSessionId: ?int, progressCode: string, payMode: int,
     *   bankId: mixed, bankNumber: mixed, branchCode: mixed, accountNo: mixed,
     *   otherNames: ?string, clientName: ?string, paymentTypeId: mixed
     * } $payment
     * @return int|null the smis receipt_no generated (or found) for this payment, or null
     *   if posting failed. Callers use this to backfill the real smis receipt number into
     *   the smisportal fee statement (see PaymentService::attemptSmisPosting()).
     */
    public function postCreditedPayment(array $payment): ?int
    {
        $billRefNumber = (string) ($payment['billRefNumber'] ?? '');
        $transId = (int) ($payment['transId'] ?? 0);
        if ($billRefNumber === '' || $transId <= 0) {
            return null;
        }

        $existingSlip = $this->findPostedSlip($billRefNumber);
        if ($existingSlip !== null) {
            $existingReceiptNo = trim((string) ($existingSlip->receipt_no ?? ''));
            return $existingReceiptNo !== '' && ctype_digit($existingReceiptNo) ? (int) $existingReceiptNo : null;
        }

        $db = $this->connection();
        if (!$this->schemaReady($db)) {
            Yii::error(
                'SMIS posting skipped for ' . $billRefNumber . ': required smis tables are not reachable.',
                self::LOG_CATEGORY
            );
            return null;
        }

        $transaction = $db->beginTransaction();
        try {
            $effectiveTransId = $transId;
            if (!SmisFeeTransaction::find()->where(['trans_id' => $transId, 'trans_type' => 'CR'])->exists()) {
                $effectiveTransId = (int) $this->createFeeTransaction($transId, $payment)->trans_id;
            }

            $slip = new SmisBankingSlip();
            $slip->setAttributes([
                'deposit_date' => $payment['paymentDate'],
                'deposit_type' => $payment['paymentTypeId'] ?? null,
                'payment_type_id' => $payment['paymentTypeId'] ?? null,
                'deposit_amount' => $payment['amount'],
                'reg_number' => $payment['registrationNumber'],
                'registration_number' => $payment['registrationNumber'],
                'other_names' => $payment['otherNames'] ?: ($payment['clientName'] ?? ''),
                'post_status' => 'POSTED',
                'post_comment' => substr((string) $payment['description'], 0, 20),
                'account_no' => $payment['accountNo'] ?? null,
                'process_date' => date('Y-m-d'),
                'pay_mode' => $payment['payMode'],
                'trans_reference' => substr((string) ($payment['gatewayReference'] ?: $billRefNumber), 0, 50),
                'branch_code' => $payment['branchCode'] ?? null,
                'last_update' => date('Y-m-d H:i:s'),
                'user_id' => $payment['userId'] ?? null,
                'drawer_name' => 'eCitizen',
                'source_reference' => $billRefNumber,
                'value_date' => date('Y-m-d H:i:s'),
                'bank_id' => $payment['bankId'] ?? null,
                'bank_number' => $payment['bankNumber'] ?? null,
            ], false);
            if (!$slip->save(false)) {
                throw new \RuntimeException('Unable to create smis banking slip: ' . json_encode($slip->getErrors()));
            }

            $receiptCounter = $this->buildReceiptCounter();
            $receiptNo = (int) $receiptCounter->last_value;
            $slip->receipt_no = $receiptNo;
            if (!$slip->save(false)) {
                throw new \RuntimeException('Unable to set smis banking slip receipt number: ' . json_encode($slip->getErrors()));
            }

            if (!SmisFeePayment::find()->where(['trans_id' => $effectiveTransId])->exists()) {
                $feePaymentAttributes = [
                    'receipt_no' => (string) $receiptNo,
                    'trans_date' => $payment['paymentDate'],
                    'trans_amount' => $payment['amount'],
                    'pay_mode' => $payment['payMode'],
                    'collection_point_id' => $payment['bankId'] ?? null,
                    'user_id' => (string) $payment['userId'],
                    'entry_date' => date('Y-m-d'),
                    'trans_id' => $effectiveTransId,
                    'academic_session' => '',
                    'authorized_by' => (string) $payment['userId'],
                    'authorized_date' => date('Y-m-d'),
                    'receipt_status' => '',
                    'exchange_rate' => 1,
                    'student_prog_curriculum_id' => $payment['studentProgCurriculumId'],
                ];
                if (!$this->columnHasDatabaseGeneratedValue($db, 'smis.fss_fee_payments', 'fee_paymt_id')) {
                    $feePaymentAttributes['fee_paymt_id'] = $effectiveTransId;
                }

                $feePayment = new SmisFeePayment();
                $feePayment->setAttributes($feePaymentAttributes, false);
                if (!$feePayment->save(false)) {
                    throw new \RuntimeException('Unable to create smis fee payment: ' . json_encode($feePayment->getErrors()));
                }
            }

            if (!$receiptCounter->save(false)) {
                throw new \RuntimeException('Unable to save smis receipt counter: ' . json_encode($receiptCounter->getErrors()));
            }

            $transaction->commit();
            return $receiptNo;
        } catch (\Throwable $exception) {
            $transaction->rollBack();
            Yii::error('SMIS posting failed for ' . $billRefNumber . ': ' . $exception->getMessage(), self::LOG_CATEGORY);
            return null;
        }
    }

    /**
     * Inserts the smis fee-transaction CR row with the given (smisportal-sourced)
     * trans_id. smis.fss_fee_transactions.trans_id has no auto-increment of its
     * own, so this id must always be supplied explicitly — which means the
     * insert can only fail if that exact id is already taken by an unrelated,
     * pre-existing smis row (a genuine historical collision, not sequence
     * drift). In that case, find the next unused trans_id on smis and use
     * that instead, logging clearly since the two databases can no longer
     * share the same trans_id for this one payment.
     */
    private function createFeeTransaction(int $transId, array $payment): SmisFeeTransaction
    {
        $attributes = [
            'trans_id' => $transId,
            'academic_progress_id' => $payment['academicProgressId'],
            'trans_date' => $payment['paymentDate'],
            'trans_type' => 'CR',
            'trans_amount' => $payment['amount'],
            'trans_desc' => substr((string) $payment['description'], 0, 150),
            'user_id' => (string) $payment['userId'],
            'receipt_status' => '',
            'exchange_rate' => 1,
            'progress_code' => $payment['progressCode'],
            'student_semester_session_id' => $payment['studentSemesterSessionId'],
        ];

        $feeTransaction = new SmisFeeTransaction();
        $feeTransaction->setAttributes($attributes, false);
        try {
            if (!$feeTransaction->save(false)) {
                throw new \RuntimeException('Unable to create smis fee transaction: ' . json_encode($feeTransaction->getErrors()));
            }
            return $feeTransaction;
        } catch (IntegrityException $exception) {
            $fallbackTransId = $this->nextAvailableTransId($transId);
            Yii::warning(
                "smis.fss_fee_transactions.trans_id {$transId} is already used by an unrelated record; "
                . "using {$fallbackTransId} instead. smisportal keeps trans_id {$transId}, smis diverges to "
                . "{$fallbackTransId} for this payment.",
                self::LOG_CATEGORY
            );

            $attributes['trans_id'] = $fallbackTransId;
            $feeTransaction = new SmisFeeTransaction();
            $feeTransaction->setAttributes($attributes, false);
            if (!$feeTransaction->save(false)) {
                throw new \RuntimeException(
                    'Unable to create smis fee transaction with fallback trans_id ' . $fallbackTransId . ': '
                    . json_encode($feeTransaction->getErrors())
                );
            }
            return $feeTransaction;
        }
    }

    /**
     * Keeps ecitizen.payment_id's auto-increment sequence in sync across both
     * databases: it's bigserial on both smisportal and smis (see migrations/
     * m260518_000001_create_ecitizen_payment_tables.php) — the only column in
     * this integration with a genuinely independent, database-native
     * auto-increment sequence on each side (fss_fee_transactions.trans_id has
     * none on smis at all, see createFeeTransaction(); fss_fee_payments and
     * fss_banking_slips are independently generated by design and never need
     * to match). Nothing currently writes to smis.ecitizen, so this is
     * forward-looking today — it just ensures neither side's sequence could
     * ever generate an id the other side already used, whichever side ends
     * up ahead.
     */
    public function reconcilePaymentIdSequence(Connection $portalDb): void
    {
        $this->reconcileSequence($portalDb, 'smisportal', $this->connection(), 'smis', 'ecitizen', 'payment_id');
    }

    /**
     * Ensures both sides' sequence for $schemaA/$schemaB.$table.$column is at
     * least GREATEST(max on either side) — whichever side is behind gets
     * bumped up to match the one that's ahead. Only touches sequences
     * actually owned by the column (see pg_get_serial_sequence); a no-op for
     * columns without one.
     */
    private function reconcileSequence(
        Connection $dbA,
        string $schemaA,
        Connection $dbB,
        string $schemaB,
        string $table,
        string $column
    ): void {
        $maxA = (int) $dbA->createCommand("SELECT COALESCE(MAX({$column}), 0) FROM {$schemaA}.{$table}")->queryScalar();
        $maxB = (int) $dbB->createCommand("SELECT COALESCE(MAX({$column}), 0) FROM {$schemaB}.{$table}")->queryScalar();
        $target = max($maxA, $maxB);
        if ($target <= 0) {
            return;
        }

        $this->advanceSequenceTo($dbA, $schemaA, $table, $column, $target);
        $this->advanceSequenceTo($dbB, $schemaB, $table, $column, $target);
    }

    private function advanceSequenceTo(Connection $db, string $schema, string $table, string $column, int $target): void
    {
        $qualifiedTable = "{$schema}.{$table}";
        $seq = $db->createCommand(
            'SELECT pg_get_serial_sequence(:table, :column)',
            [':table' => $qualifiedTable, ':column' => $column]
        )->queryScalar();
        if (empty($seq)) {
            return;
        }

        $current = $db->createCommand("SELECT last_value, is_called FROM {$seq}")->queryOne();
        $nextWouldBe = ((bool) $current['is_called']) ? ((int) $current['last_value'] + 1) : (int) $current['last_value'];
        if ($nextWouldBe > $target) {
            return;
        }

        $db->createCommand('SELECT setval(:seq, :val, true)', [':seq' => $seq, ':val' => $target])->execute();
        Yii::info(
            "Advanced sequence {$seq} for {$qualifiedTable}.{$column} to {$target}, to stay ahead of the other database.",
            self::LOG_CATEGORY
        );
    }

    /**
     * The lowest trans_id greater than both $afterTransId and the current
     * table max that isn't already taken on smis.fss_fee_transactions.
     */
    private function nextAvailableTransId(int $afterTransId): int
    {
        $maxKnown = (int) (SmisFeeTransaction::find()->max('trans_id') ?? 0);
        $candidate = max($afterTransId, $maxKnown) + 1;
        while (SmisFeeTransaction::find()->where(['trans_id' => $candidate])->exists()) {
            $candidate++;
        }

        return $candidate;
    }

    private function schemaReady(Connection $db): bool
    {
        foreach (self::REQUIRED_TABLES as $table) {
            if ($db->schema->getTableSchema($table, true) === null) {
                return false;
            }
        }

        return true;
    }

    private function columnHasDatabaseGeneratedValue(Connection $db, string $table, string $column): bool
    {
        $schema = $db->schema->getTableSchema($table, true);
        $tableColumn = $schema?->columns[$column] ?? null;

        return $tableColumn !== null && ($tableColumn->autoIncrement || $tableColumn->defaultValue !== null);
    }

    /**
     * Emulates BankingSlips::generateReceiptNo() in the SMIS admin app
     * exactly: reads the latest smis.fss_receipt_counter.last_value
     * (ordered by created_at desc, not an aggregate MAX), and returns a new,
     * unsaved counter row set to that value + 1. The caller is responsible
     * for persisting it — only once the rest of the posting succeeds — the
     * same way postFeePayments() only calls $receiptCounter->save() as the
     * final step, after everything else committed.
     */
    private function buildReceiptCounter(): SmisReceiptCounter
    {
        $lastValue = SmisReceiptCounter::find()
            ->select(['last_value'])
            ->orderBy(['created_at' => SORT_DESC])
            ->limit(1)
            ->scalar();

        $counter = new SmisReceiptCounter();
        $counter->last_value = ((int) $lastValue) + 1;

        return $counter;
    }
}
